### ISSUE TITLE
Correções

### ISSUE THREAD

**Issue by mbodock** [pipibodock/o-que-eu-sei#1]
Algumas considerações:

> Em python, todo caracter entra em formato de str. 
Na verdade temos também o tipo `bytes`, veja mais informações em: [link](https://docs.python.org/3.1/library/functions.html#bytes)

> Int, ou inteiro é uma das funções usadas por string

O `int()` na verdade é o construtor da classe `int`.  veja mais info em: [link](https://docs.python.org/3/library/functions.html#int)

> Essa função faz com que a informação ou caracter seja interpretado como um número, e em formato de inteiro. 

Na verdade faz com que seja **Convertido** tem uma diferença importante nissso.

> Uma função é um bloco de código usado para realizar uma ação. **f**acilitando suas ações e reutilizando códigos

**Comment by pipibodock** [comment]
@mbodock 

Obrigado pelas considerações. Fechamos a issue, corrigindo os pontos indicados.

Além das correções, foi adicionado novo conteúdo. fique a vontade bara retornar com mais feedback.

Obrigado.
