### ISSUE TITLE
Substituir marcação de lista por titulos

### ISSUE THREAD

**Issue by mbodock** [pipibodock/o-que-eu-sei#2]
Por favor considere a possibilidade de trocar a marcação de listas:

- str
- int

Por uma mais verbosa para os tópicos, usando subtitulos:

### int

**Comment by mbodock** [comment]
Show @pipibodock!

Considere após corrigir as issues sempre trocar um ideia aqui no chat. Nem sempre o que é pedido faz sentido.

Abraços

**Comment by pipibodock** [comment]
@mbodock 

Obrigado. Todo feedback, se é pra somar, é sempre bem vindo.

abraço.
